all:
  hosts:
    kube-node1:
      ansible_host: 172.17.0.2
      ip: 172.17.0.2
      access_ip: 172.17.0.2
    kube-node2:
      ansible_host: 172.17.0.3
      ip: 172.17.0.3
      access_ip: 172.17.0.3
    kube-node3:
      ansible_host: 172.17.0.4
      ip: 172.17.0.4
      access_ip: 172.17.0.4
    kube-node4:
      ansible_host: 172.17.0.5
      ip: 172.17.0.5
      access_ip: 172.17.0.5
    kube-node5:
      ansible_host: 172.17.0.6
      ip: 172.17.0.6
      access_ip: 172.17.0.6
  children:
    kube-master:
      hosts:
        kube-node1:
        kube-node2:
    kube-node:
      hosts:
        kube-node1:
        kube-node2:
        kube-node3:
        kube-node4:
        kube-node5:
    etcd:
      hosts:
        kube-node1:
        kube-node2:
        kube-node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
