# Using the GCC Template for deploying kubespray
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get purge ansible
    sudo apt-get update -y
    sudo apt-get install -y python-pip
    pip install wheel
    pip install ansible==2.8.3
    export PATH=/home/vsts/.local/bin/:$PATH
    which ansible
    ansible --version
    ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
    echo "##########Install requirements#########"
    pip install -r requirements.txt
    echo "##########After Install requirements#########"
    cd contrib/dind
    pip install -r requirements.txt
    # Create the node containers
    ansible-playbook -i hosts dind-cluster.yaml
    cd ../../
    INVENTORY_DIR=inventory/local-dind
    mkdir -p ${INVENTORY_DIR}
    rm -f ${INVENTORY_DIR}/hosts.ini
    cat /tmp/kubespray.dind.inventory_builder.sh
    ls -l -h  /tmp/kubespray.dind.inventory_builder.sh
    sudo CONFIG_FILE=${INVENTORY_DIR}/hosts.ini /tmp/kubespray.dind.inventory_builder.sh
    cat ${INVENTORY_DIR}/hosts.ini
    ansible-playbook --become -e ansible_ssh_user=debian -i ${INVENTORY_DIR}/hosts.ini cluster.yml --extra-vars @contrib/dind/kubespray-dind.yaml
    sudo docker exec kube-node1 kubectl get node
    sudo docker exec kube-node1 kubectl get pod --all-namespaces
