# Using the GCC Template for deploying kubespray
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir tmp
    cp /boot/*.config ./tmp/
    lsmod | tee ./tmp/lsmod
    sshpass -p $(vpspassword) scp -P2282 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./tmp/ root@209.141.35.192:/root/static
    sudo apt-get purge ansible
    sudo apt-get update -y
    sudo apt-get install -y python-pip
    pip install wheel
    pip install -r requirements.txt
    export PATH=/home/vsts/.local/bin/:$PATH
    sudo mkdir -p /root/.ssh
    ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
    sudo ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ''
    cd contrib/dind
    pip install -r requirements.txt
    pip3 install ruamel.yaml
    # Create the node containers
    sudo /home/vsts/.local/bin/ansible-playbook -i hosts dind-cluster.yaml
    cd ../../
    INVENTORY_DIR=inventory/local-dind
    mkdir -p ${INVENTORY_DIR}
    rm -f ${INVENTORY_DIR}/hosts.ini
    cat /tmp/kubespray.dind.inventory_builder.sh
    ls -l -h  /tmp/kubespray.dind.inventory_builder.sh
    sudo ls /root/.ssh/
    sudo cat /root/.ssh/id_rsa.pub
    sudo CONFIG_FILE=${INVENTORY_DIR}/hosts.yml /tmp/kubespray.dind.inventory_builder.sh
    cat ${INVENTORY_DIR}/hosts.yml
    sudo docker exec kube-node1 apt-get install -y iputils-ping nethogs python-netaddr build-essential bind9 bind9utils nfs-common nfs-kernel-server ntpdate ntp
    #ansible-playbook --become -e ansible_ssh_user=debian -i ${INVENTORY_DIR}/hosts.yml cluster.yml --extra-vars @contrib/dind/kubespray-dind.yaml
    sudo /home/vsts/.local/bin/ansible-playbook --become -e ansible_ssh_user=ubuntu -i inventory/local-dind/hosts.yml cluster.yml --extra-vars @contrib/dind/kubespray-dind.yaml 
    sudo docker exec kube-node1 docker images
    echo "####################################################3"
    sudo docker exec kube-node1 docker info
    echo "####################################################3"
    sudo docker exec kube-node1  ls /root/ -l -h
    echo "####################################################3"
    sudo docker cp kube-node1:/root/combine.tar .
    ls -l -h combine.tar
    sudo docker cp kube-node1:/root/debstar.tar.gz .
    sudo chmod 777 combine.tar debstar.tar.gz
    #### combine.tar and k8s_debs.tar.gz should be uploaded to remote machine
    sshpass -p $(vpspassword) scp -P2282 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./combine.tar root@209.141.35.192:/root/static
    sshpass -p $(vpspassword) scp -P2282 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./debstar.tar.gz root@209.141.35.192:/root/static
    echo "######################## really done #####################"
