# Using the GCC Template for deploying kubespray
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    which ansible
    ansible --version
    ls -l -h /usr/local/bin
    sudo apt-get purge ansible
    sudo apt-get update -y
    sudo apt-get install -y python-pip
    pip install wheel
    pip install ansible==2.8.3
    which ansible
    ls -l -h /usr/local/bin
    /usr/local/bin/ansible --version
    echo "################After pip#################"
    sudo pip install wheel
    sudo pip install ansible==2.8.3
    which ansible
    ls -l -h /usr/local/bin
    /usr/local/bin/ansible --version
    export PATH=/usr/local/bin:$PATH
    which ansible
    python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
    ansible --version
    echo "################After sudo pip#################"
    ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
    cd contrib/dind
    # Install ansible
    pip install -r requirements.txt
    pip install ruamel.yaml
    pip3 install ruamel.yaml
    # Create the node containers
    ansible-playbook -i hosts dind-cluster.yaml
    cd ../../
    INVENTORY_DIR=inventory/local-dind
    mkdir -p ${INVENTORY_DIR}
    rm -f ${INVENTORY_DIR}/hosts.ini
    cat /tmp/kubespray.dind.inventory_builder.sh
    ls -l -h  /tmp/kubespray.dind.inventory_builder.sh
    CONFIG_FILE=${INVENTORY_DIR}/hosts.ini /tmp/kubespray.dind.inventory_builder.sh
    ##*docker ps
    ##*cat ${INVENTORY_DIR}/hosts.ini
    ##*ansible-playbook --become -e ansible_ssh_user=debian -i ${INVENTORY_DIR}/hosts.ini cluster.yml --extra-vars @contrib/dind/kubespray-dind.yaml
    #sudo docker ps
    #sudo docker exec kube-node1 kubectl get node
    #sudo docker exec kube-node1 kubectl get pod --all-namespaces
