---
- name: restart docker
  command: /bin/true
  notify:
    - Docker | reload systemd
    - Docker | reload docker.socket
    - Docker | reload docker
    - Docker | wait for docker

- name: Docker | reload systemd
  systemd:
    daemon_reload: true

- name: Docker | reload docker.socket
  service:
    name: docker.socket
    state: restarted
  when: ansible_os_family in ['CoreOS', 'Container Linux by CoreOS']

- name: Docker | reload docker
  raw: sleep 3 && systemctl daemon-reload &&  systemctl start docker && systemctl stop docker && sleep 3 && systemctl start docker
  #service:
  #  name: docker
  #  state: restarted

- name: Docker | wait for docker
  command: "{{ docker_bin_dir }}/docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0
